---
- name : copy file to remote
  remote_user: appdynamics
  sudo: no
  hosts: remote

  tasks:
   - name: transfer mysql scripts to remote
     copy: src=/Users/parikshit.chakraborty/appd_home/automation_parikcha/ansible/{{ item }}  dest=/home/appdynamics/ mode=0755
     with_items:
      - db.sql
      - mysql.sh


   - name : Execute mysql
     command: sh /home/appdynamics/mysql.sh 


